wp-env run cli "wp option update blogname \"The Boilerplate for WordPress\""
wp-env run cli "wp option update permalink_structure \"/%postname%/\""
wp-env run cli "wp option update timezone_string \"Asia/Tokyo\""

wp-env run cli "wp language core install ja"
wp-env run cli "wp language core activate ja"

wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 1\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 2\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 3\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 4\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 5\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 6\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 7\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 8\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 9\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 10\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 11\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 12\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 13\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 14\""
wp-env run cli "wp post create --post_type=news --post_status=publish --post_title=\"News 15\""

wp-env run cli "wp term create news_category \"Media\""
wp-env run cli "wp term create news_category \"Event\""
wp-env run cli "wp term create news_category \"Press Release\""
